name: vulv-client

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - vulv-network

networks:
  vulv-network:
    external: true
